SELECT * FROM DimEmployee

SELECT 
	StartDate,
	EndDate,
	[dbo].[ANOS](StartDate,EndDate) AS 'TEMPO'
FROM DimEmployee

CREATE OR ALTER FUNCTION ANOS(@DATA1 DATE, @DATA2 DATE)
RETURNS INT
AS
BEGIN
	IF @DATA2 IS NULL
		SET @DATA2 = GETDATE()

	RETURN DATEDIFF(YEAR, @DATA1, @DATA2)

END
